#!/usr/bin/env node
/**
 * This file builds Parseleaf's standalone release artifact for the current
 * machine. It exists as a separate script because npm packaging and binary
 * packaging have different needs: npm wants the regular TypeScript build, while
 * Node SEA needs one fully bundled CommonJS entry file injected into a copied
 * `node` binary. It talks to `esbuild` to flatten the CLI into one script, to
 * Node's SEA preparation flow to create the injection blob, and to platform
 * tools like `codesign`, `postject`, and `tar` so the release workflow can ship
 * a single binary tarball per architecture.
 */

import { chmod, copyFile, mkdir, rm, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";
import { execFile as execFileCallback } from "node:child_process";

import { build } from "esbuild";

const execFile = promisify(execFileCallback);

const SENTINEL_FUSE = "NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2";
const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(scriptDirectory, "../..");

function readArgument(name) {
  const flagIndex = process.argv.indexOf(name);
  if (flagIndex === -1) {
    return null;
  }

  return process.argv[flagIndex + 1] ?? null;
}

async function runCommand(file, args) {
  // We funnel shelling out through one helper so build failures read like stage
  // failures, not like a pile of raw subprocess noise with no context.
  try {
    await execFile(file, args, {
      cwd: projectRoot,
      env: process.env
    });
  } catch (error) {
    const stderr = error instanceof Error && "stderr" in error ? String(error.stderr ?? "") : "";
    throw new Error(`Command failed: ${file} ${args.join(" ")}\n${stderr}`.trim());
  }
}

async function main() {
  const outputDirectory =
    readArgument("--output-dir") ??
    join(projectRoot, ".release", `${process.platform}-${process.arch}`);
  const bundlePath = join(outputDirectory, "parseleaf-sea.cjs");
  const blobPath = join(outputDirectory, "sea-prep.blob");
  const configPath = join(outputDirectory, "sea-config.json");
  const binaryPath = join(outputDirectory, "parseleaf");
  const tarballName = `parseleaf-${process.platform}-${process.arch}.tar.gz`;
  const tarballPath = join(outputDirectory, tarballName);
  const postjectPath = join(projectRoot, "node_modules", ".bin", "postject");

  await rm(outputDirectory, { recursive: true, force: true });
  await mkdir(outputDirectory, { recursive: true });

  // SEA can only run one embedded CommonJS script, so we bundle the CLI and all
  // filesystem-based dependencies into one deterministic entry file first.
  await build({
    absWorkingDir: projectRoot,
    bundle: true,
    entryPoints: [join(projectRoot, "src", "cli.ts")],
    format: "cjs",
    outfile: bundlePath,
    platform: "node",
    sourcemap: false,
    target: ["node22"]
  });

  await writeFile(
    configPath,
    `${JSON.stringify(
      {
        main: bundlePath,
        output: blobPath,
        disableExperimentalSEAWarning: true,
        useCodeCache: false,
        useSnapshot: false
      },
      null,
      2
    )}\n`,
    "utf8"
  );

  // The blob must be generated by the same Node version that will host it, so
  // we use the current runner's `node` executable as both the source and target.
  await runCommand(process.execPath, ["--experimental-sea-config", configPath]);
  await copyFile(process.execPath, binaryPath);

  if (process.platform === "darwin") {
    // macOS will reject blob injection into a signed binary, so we clear the
    // inherited signature before `postject` and add an ad-hoc signature after.
    await runCommand("codesign", ["--remove-signature", binaryPath]);
  }

  const postjectArgs = [
    binaryPath,
    "NODE_SEA_BLOB",
    blobPath,
    "--sentinel-fuse",
    SENTINEL_FUSE
  ];

  if (process.platform === "darwin") {
    postjectArgs.push("--macho-segment-name", "NODE_SEA");
  }

  await runCommand(postjectPath, postjectArgs);

  if (process.platform === "darwin") {
    await runCommand("codesign", ["--sign", "-", binaryPath]);
  }

  await chmod(binaryPath, 0o755);

  // The tarball is the artifact GitHub Releases and Homebrew both consume, so
  // we package only the runnable binary rather than the intermediate SEA files.
  await runCommand("tar", ["-czf", tarballPath, "-C", outputDirectory, "parseleaf"]);
  await rm(bundlePath, { force: true });
  await rm(blobPath, { force: true });
  await rm(configPath, { force: true });

  process.stdout.write(`${tarballPath}\n`);
}

main().catch((error) => {
  const message = error instanceof Error ? error.message : String(error);
  process.stderr.write(`build-sea: ${message}\n`);
  process.exitCode = 1;
});
